# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build & Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2
        with:
          version: 8.2.0
          run_install: true
          run_build: false
          working_directory: ${{env.working-directory}}
      - run: pnpm config set enable-pre-post-scripts true
        working-directory: ${{env.working-directory}}
      - run: pnpm run -r build
        working-directory: ${{env.working-directory}}
      - run: pnpm run -r copy:build
        working-directory: ${{env.working-directory}}
      - run: pnpm run -r copy:manifests
        working-directory: ${{env.working-directory}}
      - run: ls -ah chassis/build
        working-directory: ${{env.working-directory}}
